### ISSUE TITLE
Sourcemapping stopped working after upgrade of ember to 2.18

### ISSUE THREAD

**Issue by lubosek** [san650/ember-qunit-source-map#7]

**Comment by san650** [comment]
@lubosek thanks for reporting the issue, I'll investigate it.

**Comment by lubosek** [comment]
well, I wanted to add some details but it seems that I'm unable to reproduce it now... :-( sorry for false alarm...

**Comment by san650** [comment]
@lubosek no worries, let us know if you get the same error again.
